spring.datasource.url=jdbc:mysql://ankittest02.cn0rhtxawfvo.us-east-1.rds.amazonaws.com:3306/ankittest02
spring.datasource.username=admin
spring.datasource.password=123456789
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080